# Generated by Django 3.2.8 on 2022-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220531_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
