# Generated by Django 3.2.8 on 2022-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventgoing'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aors', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
