# Generated by Django 3.2.8 on 2022-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='mangingfevent',
            field=models.CharField(default='Not selected', max_length=50),
        ),
    ]
