# Generated by Django 3.2.8 on 2022-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
