# Generated by Django 3.2.8 on 2022-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentevent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='grade',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
