# Generated by Django 3.2.8 on 2022-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentevent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultpublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
